version: '2'

tasks:
  install:
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    method: checksum
  build:
    deps: [install]
    cmds:
      - npm run build
    sources:
      - src/**/*.ts
    generates:
      - dist
  test:
    cmds:
      - npm test
    sources:
      - src/**/*.ts
  default:
    deps: [build]
    cmds:
      - node dist/index.js
  docker:build:
    cmds:
      - docker build -t no0dles/node-taskfile-demo .
  docker:publish:
    cmds:
      - docker push no0dles/node-taskfile-demo
